# Generated by Django 5.x on 2026-02-10
from __future__ import annotations

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Call",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.TextField()),
                ("storage_path", models.TextField()),
                ("status", models.CharField(db_index=True, default="queued", max_length=32)),
                ("created_at", models.DateTimeField(db_index=True, default=datetime.datetime.utcnow)),
                ("updated_at", models.DateTimeField(default=datetime.datetime.utcnow)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("language_code", models.CharField(blank=True, max_length=32, null=True)),
                ("stt_model", models.CharField(blank=True, max_length=128, null=True)),
                ("with_diarization", models.BooleanField(blank=True, null=True)),
                ("num_speakers", models.IntegerField(blank=True, null=True)),
                ("prompt", models.TextField(blank=True, null=True)),
                ("prompt_pack", models.CharField(blank=True, max_length=64, null=True)),
                ("glossary_terms", models.TextField(blank=True, null=True)),
                ("transcript_text_path", models.TextField(blank=True, null=True)),
                ("transcript_json_path", models.TextField(blank=True, null=True)),
                ("analysis_json_path", models.TextField(blank=True, null=True)),
                ("qa_json_path", models.TextField(blank=True, null=True)),
                ("summary_json_path", models.TextField(blank=True, null=True)),
                ("raw_llm_path", models.TextField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={"db_table": "call"},
        ),
    ]
