# Generated by Django 5.x on 2026-02-10
from __future__ import annotations

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RealtimeCall",
            fields=[
                (
                    "call_id",
                    models.CharField(editable=False, max_length=128, primary_key=True, serialize=False),
                ),
                ("provider", models.CharField(default="generic", max_length=64)),
                ("status", models.CharField(db_index=True, default="active", max_length=32)),
                ("created_at", models.DateTimeField(db_index=True, default=datetime.datetime.utcnow)),
                ("updated_at", models.DateTimeField(db_index=True, default=datetime.datetime.utcnow)),
                ("agent_id", models.CharField(blank=True, max_length=128, null=True)),
                ("customer_id", models.CharField(blank=True, max_length=128, null=True)),
                ("last_speaker", models.CharField(blank=True, max_length=32, null=True)),
                ("last_text", models.TextField(blank=True, default="")),
                ("sentiment_score", models.FloatField(default=0.0)),
                ("risk_score", models.FloatField(default=0.0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={"db_table": "realtime_call"},
        ),
        migrations.CreateModel(
            name="RealtimeEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("occurred_at", models.DateTimeField(db_index=True, default=datetime.datetime.utcnow)),
                ("event_type", models.CharField(db_index=True, max_length=64)),
                ("speaker", models.CharField(blank=True, max_length=32, null=True)),
                ("text", models.TextField(blank=True, default="")),
                ("sentiment", models.FloatField(blank=True, null=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "realtime_call",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="events",
                        to="app.realtimecall",
                    ),
                ),
            ],
            options={"db_table": "realtime_event"},
        ),
        migrations.CreateModel(
            name="SupervisorAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("created_at", models.DateTimeField(db_index=True, default=datetime.datetime.utcnow)),
                ("alert_type", models.CharField(db_index=True, max_length=64)),
                ("severity", models.CharField(db_index=True, max_length=16)),
                ("message", models.TextField()),
                ("acknowledged", models.BooleanField(db_index=True, default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "realtime_call",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="alerts",
                        to="app.realtimecall",
                    ),
                ),
            ],
            options={"db_table": "supervisor_alert"},
        ),
        migrations.AddIndex(
            model_name="realtimeevent",
            index=models.Index(fields=["realtime_call", "-occurred_at"], name="realtime_ev_realtim_b44ca4_idx"),
        ),
        migrations.AddIndex(
            model_name="realtimeevent",
            index=models.Index(fields=["event_type", "-occurred_at"], name="realtime_ev_event_t_8decf4_idx"),
        ),
        migrations.AddIndex(
            model_name="supervisoralert",
            index=models.Index(
                fields=["realtime_call", "acknowledged", "-created_at"],
                name="supervisor__realtim_6bc46f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="supervisoralert",
            index=models.Index(fields=["severity", "-created_at"], name="supervisor__severit_f58eb4_idx"),
        ),
    ]
